### ISSUE TITLE
执行mdye sync-params时报错

### ISSUE THREAD

**Issue by vinsun122** [mingdaocom/plugin_view_samples#3]
执行`mdye sync-params`时报错
<img width="960" alt="image" src="https://github.com/mingdaocom/plugin_view_samples/assets/41813153/c6823963-94d4-4134-92bd-958c2a6fc1cf">

**Comment by peidayu** [comment]
截图看出的信息有限，麻烦贴下运行命令后的完整输出截图。
看着像是请求时发生了问题，下面问题一并确认下
1. 报错前控制台是否已授权完成，已授权状态命令行会显示 当前登录用户：***
2. 现在使用的明道云是否是SaaS版本，访问的主域名是不是 www.mingdao.com

**Comment by vinsun122** [comment]
是授权失效造成的，大意了

**Comment by peidayu** [comment]
好的，正常会提示失效重新登录的，我们这边看下是不是哪里出了问题。
